name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: purescript-contrib/setup-purescript@main

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install -g spago
          npm install

      - name: Build source
        run: npm run-script build

      - name: Run tests
        run: npm run-script test
